language: node_js
node_js:
  - 12.13.0
branches:
  only:
    - master
script:
  - 'yarn build'
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT